# Generated by Django 2.2.9 on 2020-01-28 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=355, verbose_name='заголовок')),
                ('text', models.TextField(blank=True, null=True, verbose_name='текст страницы')),
                ('active', models.BooleanField(default=False, verbose_name='Вкл\\Выкл')),
                ('template', models.CharField(default='page/index.html', max_length=500, verbose_name='шаблон')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='url')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
                'unique_together': {('slug',)},
            },
        ),
    ]
