# Generated by Django 2.2.9 on 2020-01-30 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='template',
            field=models.CharField(default='pages/index.html', max_length=500, verbose_name='шаблон'),
        ),
    ]
