# Generated by Django 2.2.9 on 2020-01-30 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200130_1322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.CharField(max_length=200, unique=True, verbose_name='url'),
        ),
    ]
