# Generated by Django 2.2.9 on 2020-01-28 18:05

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('is_auth', models.BooleanField(default=False, verbose_name='Для зарегистрированных или нет')),
                ('activate', models.BooleanField(default=False, verbose_name='Вкл\\Выкл')),
            ],
            options={
                'verbose_name': 'Меню',
                'verbose_name_plural': 'менюшки',
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='название латиницей')),
                ('title', models.CharField(max_length=250, verbose_name='название меню')),
                ('status', models.BooleanField(default=False, verbose_name='Вкл\\Выкл')),
                ('is_auth', models.BooleanField(default=False, verbose_name='Для зарегистрированных или нет')),
                ('anchor', models.CharField(blank=True, max_length=255, null=True, verbose_name='якорь')),
                ('url', models.CharField(blank=True, max_length=300, null=True, verbose_name='ссылка на внешний ресурс')),
                ('active', models.BooleanField(default=False, verbose_name='Вкл\\Выкл')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu', verbose_name='меню')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.MenuItem', verbose_name='Родительский пункт')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
