# Generated by Django 2.2.9 on 2020-01-30 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200130_1325'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Меню', 'verbose_name_plural': 'меню'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'verbose_name': 'пункты меню', 'verbose_name_plural': 'пункты меню'},
        ),
    ]
